esl:
  host: "192.168.13.137"
  port: 8021
  password: "ClueCon"
  timeout: 10s
  reconnect_interval: 5s
  max_reconnect_attempts: 10

# Event filtering and processing
events:
  subscribe_events:
    - "CHANNEL_CREATE"
    - "CUSTOM callcenter::info"

  event_field_mappings:
    # Agent status events for ASM - with field mapping
    - event_types: ["CUSTOM callcenter::*"]
      mappings:
        - from: "Event-Date-Timestamp"
          to: "changeTime"
          transforms: [":int", ":divide:1000000", ":round"]
        - from: "Cc-Action"
          to: "action"
          transforms: ["trim"]
        - from: "Cc-Agent"
          to: "agentId"
          transforms: ["trim"]
        - from: "Cc-Queue"
          to: "queueName"
          transforms: ["trim"]
        - from: "Cc-Agent-State"
          to: "state"
          transforms: ["url_decode"]
        - from: "Cc-Agent-Status"
          to: "status"
          transforms: ["url_decode"]
      field_filters:
        include_headers:
          - "Event-*"
          - "Unique-ID"
          - "Cc-*"
        exclude_headers:
          - "*-Ipv6"
          - "*-Switchname"
        include_fields:
          - "changeTime"
          - "action"
          - "agentId"
          - "state"
          - "status"
        exclude_fields:
        #- "headers"
        #- "event_subclass"
        #- "event_name"
        include_body: false

    # # Channel events for Call State Manager - NO field mapping, keep raw format
    # - event_types: ["CHANNEL_*"]
    #   mappings: []
    #   field_filters:
    #     include_headers:
    #       - "Event-*"
    #       - "Unique-ID"
    #       - "Channel-*"
    #       - "Caller-*"
    #       - "Call-Direction"
    #       - "variable_*"
    #       - "Application*"
    #       - "Hangup-Cause"
    #       - "Bridge-*"
    #       - "Other-Leg-*"
    #       - "Originator-*"
    #     exclude_headers:
    #       - "*-Ipv6"
    #       - "*-Switchname"
    #       - "*-Calling-*"
    #     include_body: false

# HTTP destinations
http:
  destinations:
    - name: "asm"
      url: "http://192.168.13.134:31804/api/v2/status/notify-status-change"
      method: "POST"
      headers:
        Content-Type: "application/json"
      timeout: 5s
      retry:
        max_attempts: 2
        backoff: "fixed"
        initial_delay: 2s
        max_delay: 5s
      event_filters:
        - "CUSTOM callcenter::*"
      filter_logic: "AND"
      filters:
        - field: "Cc-Action"
          operator: "regex"
          value: "^(agent-)(status|state)(-change)$"

    - name: "call-state-manager"
      url: "http://10.196.26.169:30000/events"
      method: "POST"
      headers:
        Content-Type: "application/json"
      timeout: 5s
      retry:
        max_attempts: 3
        backoff: "exponential"
        initial_delay: 1s
        max_delay: 10s
      event_filters:
        - "CHANNEL_*"

# Logging
logging:
  level: "debug"
  format: "console"
  output: "stdout"